### ISSUE TITLE
Error 403; "SyntaxError: Unexpected token S in JSON at position 4" with melcloud-device or melcloud-overide

### ISSUE THREAD

**Issue by Meewis** [ysimonx/node-red-contrib-melcloud#11]
Hi,

With melcloud-connect I get the correct return of data; BuildingID, DeviceID. Then I fill out the settings for the melcloud-device and connect it to a default inject node and a debug node (likewise melcloud-device.png). Then when i push the inject node, I get an error message at the debug node:
{"statusCode":403,"payload":"\r\n{ Success: false, ErrorMessage: \"Forbidden\"}","error":"SyntaxError: Unexpected token S in JSON at position 4"}

Am I doing something wrong?

Kind regards, Wilco

**Comment by mengi69** [comment]
I have the same error... it happens to me the same as it happens to you, but I can't find help anywhere. I have asked here, but I do not receive an answer.

**Comment by Meewis** [comment]
Found the cause of my problems; wrong DeviceID. It should be copied from: payload[0].Structure.Floors[0].Devices[0].DeviceID

Kind regards, Wilco

**Comment by mengi69** [comment]
![image](https://user-images.githubusercontent.com/4528723/197409823-1b414912-b13e-4677-ab59-13764171b4b9.png)

Me, I try to put the Set of the temperature of the hot water tank, but it puts, not defined

![image](https://user-images.githubusercontent.com/4528723/197409857-1d877cc8-a8ae-4732-8322-02dcaebfde06.png)

**Comment by Meewis** [comment]
You only can use the terms as shown in the example. SetTankwaterTemperatue does not exist.

**Comment by mengi69** [comment]
But I would like to use it to change the temperature of my hot water tank for the shower.

**Comment by Meewis** [comment]
It is not foreseen in this code and also not in the code of this type of Mitsubishi equipment....

**Comment by mengi69** [comment]
Okay, I didn't know... let's see if one day they solve it, to be able to put the temperature.

Thank you very much.
