### ISSUE TITLE
Faulty code in melcoud-connect.js

### ISSUE THREAD

**Issue by Meewis** [ysimonx/node-red-contrib-melcloud#12]
After this fault and a crash of NodeRed, I got this message:
25 Oct 03:37:24 - [red] Uncaught Exception:
25 Oct 03:37:24 - [error] ReferenceError: msg is not defined
    at /data/node_modules/node-red-contrib-melcloud/melcloud-connect.js:256:44
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

The solution:
At line 256:  }).catch(err => {
This should be:  }).catch(msg => {

Kind regards, Wilco

**Comment by ysimonx** [comment]
Hello

let's fix it ;-)

thx

**Comment by ysimonx** [comment]
Hi @Meewis 

I just pushed a little fix with https://flows.nodered.org/node/node-red-contrib-melcloud
can you try please ?

**Comment by Meewis** [comment]
Test is running, it needs some days to be sure of the good result...

**Comment by Meewis** [comment]
As far I can see, it works alright, no problems.

**Comment by ysimonx** [comment]
> 

Thx
