### ISSUE TITLE
Login issue

### ISSUE THREAD

**Issue by Drahos-X** [ysimonx/node-red-contrib-melcloud#17]
"melcloud-connect" is reporting "Error: unable to verify the first certificate" [10.05.2023].
Username and password are OK, I am able to login to the MELCloud on their web page.
Any idea?

**Comment by MasterChips1** [comment]
I have the same problem from Today.
Changed password, but didn't solve it.

Units are still remote accessible from app and website.

**Comment by Drahos-X** [comment]
I tested HTTP commands from Postman. If I switch off SSL certificate testing, everything works.
I guess this is a problem with MELCloud server and their certificates.

**Comment by ghost** [comment]
Same problem here, strange why this happens all of a sudden...

**Comment by h1ght0wer** [comment]
Same issue here.
I tried to create a new credential in Node Red, still no change.
MELCloud via browser is working fine for me as well

**Comment by ysimonx** [comment]
Thanks everyone ! I will update the module as soon as I am back home in a next few hours

**Comment by romainlataye** [comment]
Temporarily, you can add in setting.js (nodered) : process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";
Before the module.exports line.

**Comment by ysimonx** [comment]
Hi @romainlataye @h1ght0wer @MPowerData @MasterChips1 @Drahos-X 
I do not have this issue anymore

do you confirm ?

thx

**Comment by h1ght0wer** [comment]
Mine seems to work again, thanks for looking into it 😊 even tho it fixed it self

**Comment by Drahos-X** [comment]
It is working now. Definitely the problem was related to the MELCloud server configuration.
