### ISSUE TITLE
Language setting

### ISSUE THREAD

**Issue by 000101** [ysimonx/node-red-contrib-melcloud#2]
Hi

I'm new to Node-red but this is proving a really helpful node for me.  I'm using it with an ASHP, not air conditioning but can work with the device data, ignoring blade angles, fan speed, etc.

It does however, set my MelCloud account to French every time I trigger the nodes.  I had a look through and think I spotted that in melcloud.js at line 40:
```
"Language":7,
```
Is it possible to have this as a selectable option, as I believe I'd like 6 for English?  I'm new to javascript so could easily be mistaken.

Thanks

**Comment by ysimonx** [comment]
Hi

I will take a look tomorrow :)

**Comment by ysimonx** [comment]
Hi @000101 

I just removed language setting from the authentification request
can you test on your node-red please ?
new node extension : Version: 1.3.7

**Comment by 000101** [comment]
Perfect - thank you!
