### ISSUE TITLE
Aerothermal Motor Frequency Sensor Reading

### ISSUE THREAD

**Issue by mengi69** [ysimonx/node-red-contrib-melcloud#21]
Hello and thanks for the thread.

I don't know if it is the right place, but I would like to ask if you know how I can read the working frequency of the Aerotermia motor, in order to know if it has had more or less demand.

I don't know if these nodes can be read, but I think it should be possible, since with an ESP32 from HA, they are doing it.

If I can contribute anything else, do not hesitate to ask me.

Thank you.

**Comment by ysimonx** [comment]
Hi @mengi69 : no, this is not the right place
sorry

**Comment by mengi69** [comment]
First of all, I apologize for the inconvenience and for my English, since I use Google Translate.

What I want to know is if this node, which gives me a lot of information, the MelCloud node, among all the values, which are many, is there one that is the working frequency sensor, I am not referring to other types of nodes .


I hope I have explained myself a little better now.

Thank you.
