### ISSUE TITLE
New option for mode: dry

### ISSUE THREAD

**Issue by AlfAlex** [ysimonx/node-red-contrib-melcloud#3]
Would be nice to add another mode to the list of already possibilities (next to cooling, heat, auto, ...): Dry (value 2)

**Comment by ysimonx** [comment]
Hello @AlfAlex 

Can you test this feature with node-red-contrib-melcloud 1.3.8 
i just pushed please ?

**Comment by AlfAlex** [comment]
Thanks. Works perfect (and is exactly the same change as I have done it at my place)
