### ISSUE TITLE
Names for fan speed

### ISSUE THREAD

**Issue by AlfAlex** [ysimonx/node-red-contrib-melcloud#5]
Nice to have:
1: Lowest
2: Low
3: Medium
4: High
5: Max

Instead of numbers only

**Comment by ysimonx** [comment]
Hi @AlfAlex 

For this issue, I just pushed node-red-contrib-melcloud 1.4.0

I would be happy if you can test this please :)

**Comment by AlfAlex** [comment]
It works.
Just thinking if if would be better to show both values (name and integer) or just the name.

**Comment by ysimonx** [comment]
Hum … I agree with your suggestion, let’s do it

**Comment by ysimonx** [comment]
@AlfAlex 
Updated node-red-contrib-melcloud (1.4.1)
node-red-contrib-melcloud 1.4.1

**Comment by AlfAlex** [comment]
For me that's fine!
Thanks

**Comment by ysimonx** [comment]
thank you for your help. I felt alone with this project ;-)

**Comment by AlfAlex** [comment]
My pleasure, it did help me a lot because all other melclould  projects I could not use. At least without so less work.
And I did not have to deal (read about it) with the API for myself.
