### ISSUE TITLE
mode

### ISSUE THREAD

**Issue by Gregor-Weissenborn** [ysimonx/node-red-contrib-melcloud#6]
Setting the operation mode is not working

**Comment by ysimon-eurevia** [comment]
Hi @Gregor-Weissenborn : thank you, i will test tonight :)

**Comment by Gregor-Weissenborn** [comment]
I noticed that it is not mentioned in melcloud-connect.js lines 168 - 211.

**Comment by ysimonx** [comment]
Hello @Gregor-Weissenborn : I made some tests

While you can change the "mode" with the melcloud-device node, 
cf
<img width="531" alt="Capture d’écran 2022-01-25 à 21 18 54" src="https://user-images.githubusercontent.com/1449867/151053076-788b4530-366d-403f-ad08-630e75f59eff.png">

I understood that you tried to change the mode value thanks to a input message payload containing mode value
 
 I made some changes, without many tests, can you take a look and tell me if it's ok for you
 
 Thank you

**Comment by ysimonx** [comment]
mode value should be one of



 "auto",  "heat", "dry",  "fan","cooling"

**Comment by Gregor-Weissenborn** [comment]
I confirm it as working by now.
Thanks a lot!
You might add it to the documentation. :-)
