### ISSUE TITLE
set external room temperature

### ISSUE THREAD

**Issue by 11awe** [ysimonx/node-red-contrib-melcloud#9]
Hi,

thanks for creating this node, made my day realizing the connection of solar power with AC devices.

1. Is it possible to set an external room temperature value to MEL cloud? I would like to have the AC-control listen to my HomeMatic temperature sensor and not its internal one. They differ up to 2 deg.

2. Whenever I send a number (1/3/8) with command "mode" the node does not pass through msg.payload. The status does only change by mobile app. Any ideas?

**Comment by ysimonx** [comment]
Hello @11awe 

you should be able to set temperature by sending an msg.device json data with a "function" node

<img width="1137" alt="Capture d’écran 2022-03-28 à 23 47 23" src="https://user-images.githubusercontent.com/1449867/160492796-1b5ee5b6-bbfd-4562-9b27-b4b98aa6b1f7.png">


msg.device = {
    
    "command": {
        "temperature": 20,
        "mode":"auto"
    }
}
return msg;
<img width="651" alt="Capture d’écran 2022-03-28 à 23 47 52" src="https://user-images.githubusercontent.com/1449867/160492879-3c9c6499-780c-42b5-ab90-5e3dbf9a1caf.png">

**Comment by 11awe** [comment]
Thanks a lot, that works properly. I recommend to add e.g. "mode": "cooling" in your example files because sending a string is not self explaining for rookies like me.

About my second question I think you got me wrong:
I want to exchange the RoomTemperature (internal device sensor?) by external HomeMatic temp sensor, because the values differ up to 2°C
